language: ruby
rvm:
  - 2.2
install: true
script:
  - gem install jekyll -v 3.4.3 --no-ri --no-rdoc
  - gem install jekyll-feed
  - gem install bitballoon
  - gem install jekyll-feed
  - gem install jekyll-tagging-related_posts
  - gem install i18n
  - jekyll build
  - bitballoon deploy ./_site --site-id $SITE_ID --access-token $ACCESS_TOKEN
# deploy:
#  skip_cleanup: true
#  provider: bitballoon
#  site-id:
#    secure: ENV['SITE_ID']
#  access-token:
#    secure: ENV['ACCESS_TOKEN']
#  local-dir: "_site/"
