language: ruby
rvm:
  - 2.2
install: true
script:
  - gem install jekyll -v _3.4.3_ --no-ri --no-rdoc
  - gem install minima
  - gem install jekyll-feed
  - jekyll build
deploy:
  provider: bitballoon
  site-id:
    secure: <%= ENV['SITE_ID'] %>
  access-token:
    secure: <%= ENV['ACCESS_TOKEN'] %>
  local-dir: "_site/"
