backend:
  name: git-gateway
  branch: master
# This line should *not* be indented
publish_mode: editorial_workflow
media_folder: "images/upload"
collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"

